### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by shimonomihs** [ktprograms/Ohms_Now#10]
How/where can I add translation, I want to transle the app to Czech

**Comment by ktprograms** [comment]
Hi! Thanks for your interest in my app. There are three files that will need to be translated. I think the language code for Czech is `cs`. But I think F-Droid uses a longer form: `cs-CZ`, right?

Please fork the repository and add a folder called `cs-CZ` in `Ohms_Now/fastlane/metadata/android/` then in that folder add a `full_description.txt` and a `short_description.txt`. Here is the link to the English version for reference: [full_description.txt](https://github.com/ktprograms/Ohms_Now/blob/master/fastlane/metadata/android/en-US/full_description.txt) and [short_description.txt](https://github.com/ktprograms/Ohms_Now/blob/master/fastlane/metadata/android/en-US/short_description.txt).

Then please create a folder called `values-cs` in `Ohms_Now/app/src/main/res/`. Copy the English [strings.xml](https://github.com/ktprograms/Ohms_Now/blob/master/app/src/main/res/values/strings.xml) file into that folder, and translate the colour names.

Here is one of the colour items in the file: `<string name="band_menu_black">0\t\tBlack</string>` and it should be translated to something like this: `<string name="band_menu_black">0\t\t`**replace here**`</string>`. Please keep the number and the `\t\t` and only replace the colour.

Thanks!
