### ISSUE TITLE
Feature request: other components beyond resistors

### ISSUE THREAD

**Issue by denilsonsa** [ktprograms/Ohms_Now#13]
I know this is a bit outside the scope, and I know I myself will rarely use it (because electronics as a hobby is something I do once in a blue moon)... Still, it would be nice to transform this app into a reference for multiple electronics components.

In special, I think about capacitors, which are sometimes identified with a three-digit number. Just like resistors, two digits are for the value, and one for the multiplier.

I'm pretty sure there are other components worth decoding (SMD resistors?), but the capacitor was the only one I interacted with (hobbyist, remember?).

Related links:

* [Ceramic capacitors: how to read 2-digit markings?](https://electronics.stackexchange.com/q/18102)
* [Ceramic capacitors: how to read 3-digit plus 1-letter markings?](https://electronics.stackexchange.com/q/16636)
* [Vishay Draloric - Ceramic Singlelayer Capacitors](https://www.vishay.com/docs/22019/cergenin.pdf) (pages 15 and 16)

**Comment by ktprograms** [comment]
Hi, I've just added ceramic capacitor decoding. The update should be on F-Droid soon.
