### ISSUE TITLE
Dark mode broken

### ISSUE THREAD

**Issue by MarcelWaldvogel** [ktprograms/Ohms_Now#16]
In dark mode, black and white rings are inverted. This should be fixed. I don't know whether it is my phone or #1 never fully worked. Let me know if your phone behaves better.

Also, orange rings are very pale and "none" (20% tolerance) is beige.

![Screenshot](https://user-images.githubusercontent.com/3014737/148601962-caec8a50-3ec6-4aa9-9b84-44d10bb70eb7.jpg)

**Comment by ktprograms** [comment]
I think there may be a problem with the way your phone implements dark mode. On the emulator it looks like this:
![device-2022-01-10-084851](https://user-images.githubusercontent.com/71804605/148708095-e9e7ecfd-3dc9-4c79-860c-c067b644fccd.png)

**Comment by MarcelWaldvogel** [comment]
Does this mean that you [do not provide your own dark colors](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme), but let the OS choose? Then, there is nothing preventing the OS to chose whatever colors it considers suitable. So, it might be a good idea to declare that you are dark-aware and use the system colors for background and text, but keep the other colors constant.

**Comment by ktprograms** [comment]
@MarcelWaldvogel Hi, can you please try building from https://github.com/ktprograms/Ohms_Now/commit/3a4ae48f324a5f4ba872a9e1b86f32cf5dc4c808, and seeing if the issue is resolved?

**Comment by ktprograms** [comment]
@MarcelWaldvogel Can you please take a look at whether this is fixed for you by https://github.com/ktprograms/Ohms_Now/commit/3a4ae48f324a5f4ba872a9e1b86f32cf5dc4c808? I want to wait for your confirmation before tagging a release.

**Comment by MarcelWaldvogel** [comment]
Sorry for the delay, I had to run through hoops to get a running Android SDK talk to my phone (including having to get manufacturer's permission before I could install over USB! Yikes!).

Now white is white, but black is also white. So some progress is visible ;-)

**Comment by MarcelWaldvogel** [comment]
I was playing around with adding black to `colors.xml` and the hex value in `Colors.kt`. It seems that MIUI is changing everything below a particular threshold to white, so even e.g. `0xFF335533` (a darkish green) is rendered as white. A web search shows that MIUI behaves badly in dark mode and that it is recommended to turn of dark mode for apps which are broken by MUI 12.

I have not found advice of how to work around that problem, so, I've disabled "Settings→Display→More Dark mode options→Adjust text and backgrounds automatically", which then shows a list of applications where one can disable this forced dark mode, which I did for Ohms Now.

So it seems there is not much that can be done except this and shout at Xiaomi. Sorry to have bothered you!

**Comment by ktprograms** [comment]
> I was playing around with adding black to `colors.xml` and the hex value in `Colors.kt`. It seems that MIUI is changing everything below a particular threshold to white, so even e.g. `0xFF335533` (a darkish green) is rendered as white. A web search shows that MIUI behaves badly in dark mode and that it is recommended to turn of dark mode for apps which are broken by MUI 12.


That's quite interesting.

> I have not found advice of how to work around that problem, so, I've disabled "Settings→Display→More Dark mode options→Adjust text and backgrounds automatically", which then shows a list of applications where one can disable this forced dark mode, which I did for Ohms Now.


Glad you found a solution.

> So it seems there is not much that can be done except this and shout at Xiaomi. Sorry to have bothered you!


Did you find any way to force not changing colors from code?

**Comment by MarcelWaldvogel** [comment]
> Did you find any way to force not changing colors from code?

No, unfortunately not, therefore I reverted to disabling the forcing in the settings. Otherwise, I would have recommended (and maybe even implemented) a change. Sorry!

**Comment by ktprograms** [comment]
On Fri Jan 21, 2022 at 10:41 PM +08, Marcel Waldvogel wrote:
> > Did you find any way to force not changing colors from code?
>
> No, unfortunately not, therefore I reverted to disabling the forcing in the settings. Otherwise, I would have recommended (and maybe even implemented) a change. Sorry!

No need to be sorry. This seems to be Xiaomi's fault
Although, to confirm, the fix I did of symlinking the colors.xml to the
dark theme folder should still be kept, right?

**Comment by MarcelWaldvogel** [comment]
I don't know enough about Android color management, but does not seem to be detrimental, on the opposite. I would keep it.

**Comment by ktprograms** [comment]
On Sat Jan 22, 2022 at 2:37 PM +08, Marcel Waldvogel wrote:
> I don't know enough about Android color management, but does not seem to be detrimental, on the opposite. I would keep it.

Ok, thanks for confirming. I'll tag a release _soonish_.
