### ISSUE TITLE
Feature request: Going back one color

### ISSUE THREAD

**Issue by MarcelWaldvogel** [ktprograms/Ohms_Now#2]
Thanks for the app!

When needing to advance several colors at once, I happen to click too fast and going too far. Having forward another 9 colors can be annoying and the same mistake may happen again.

How about implementing one or both of these:
1. In addition to tapping, which gives +1, it is also possible to slide up or down on the color to result in +/-n.
2. Long-press on the color gives a popup with all 10 colors for a quick choice. (Or only the 3x3 other colors; might look better.)

**Comment by ktprograms** [comment]
Thanks for the suggestions. I'll look into the sliding soon, but I've made an updated version with long click to show a popup, which (hopefully) will be on F-Droid soon.
