### ISSUE TITLE
Feature request: Advancing to next/previous resistance

### ISSUE THREAD

**Issue by MarcelWaldvogel** [ktprograms/Ohms_Now#3]
When thinking about sliding: How about sliding left/right (maybe hinted at by arrows near the wires) to the next value of the [E12/E24 series](https://en.wikipedia.org/wiki/E_series_of_preferred_numbers), depending on the current tolerance setting?

**Comment by colinner** [comment]
That's a great idea! I second this feature. This would be ideal for reverse value lookup.

**Comment by ktprograms** [comment]
What a coincidence! I'm just done implementing it, so it should hopefully be available on F-Droid in a few days.
