### ISSUE TITLE
Feature request: Add support for 3, 5 & 6 band resistors

### ISSUE THREAD

**Issue by mike-cr** [ktprograms/Ohms_Now#6]
It would be nice to cover all types and include temperature coefficient if applicable

**Comment by ktprograms** [comment]
Hi, so 5 band resistors have a 1% or tighter tolerance, but at what tolerance should it switch to 6 bands and include the temperature coefficient?

**Comment by tinnus-napbus** [comment]
The number of bands aren't a function of tolerance, they're just separate styles. Usually 5 bands have more precise tolerances (cos what's the point of an extra digit if the tolerance is real loose?) but there's no actual rule about it. In principle they could have 10% or whatever. Probably better to have a band # selector than to try to make them flow together

**Comment by ktprograms** [comment]
Oh I see. Yes, I think having a button to change the number of bands would work. But 3 band resistors are always 20% tolerance right?

BTW what E-series should be used for each tolerance (eg. E6 for 20%, E12 for 10%, etc.)?

**Comment by tinnus-napbus** [comment]
I wouldn't trust 3 band resistors to be in an E6 series since they're usually old and the 20% is more of a safe assumption than a specification. I think typically others will be in those series but there are probably exceptions and there's also `E96 + E24` which includes E24 values with 1% tolerance tolerances

**Comment by ktprograms** [comment]
As I said #3, I've implemented sliding left/right to go to the previous/next E-series value, but it is still possible to tap the bands to go to any value. The sliding is just a faster way to get to more common values in each tolerance range.

So would this list be correct?
20% -> E6
10% -> E12
5% -> E24
2% -> E48
1% -> E96
0.5% or tighter -> E192

**Comment by tinnus-napbus** [comment]
oh right that makes sense I didn't understand what you were doing with the E series

Yeah if you're still able to key in non-standard values then those mappings would be fine

**Comment by ktprograms** [comment]
Ok. Thanks!

BTW do you have any idea why F-Droid seems to take so long on each update?

**Comment by tinnus-napbus** [comment]
Not sure but I think at some point someone actually manually signs the package so maybe they have a backlog
